### ISSUE TITLE
对xcode7.2无效么?

### ISSUE THREAD

**Issue by drduan** [qfish/XActivatePowerMode#22]
对xcode7.2无效么?重启xcode edit里没有选项

**Comment by qfish** [comment]
明哥好！我看看.

**Comment by qfish** [comment]
刚试了下，7.2 可以。把代码下载下来，然后 cmd+b，重启Xcode，会提示 是否加载插件，点击 <kbd>Load Bundle</kbd>，应该就有了。

**Comment by drduan** [comment]
恩 成功了
